blank_issues_enabled: true
contact_links:
  - name: Question / Discussion
    url: https://github.com/kadiryonak/DeepArticle/discussions
    about: Ask questions and discuss ideas with the community.
