"""
Supplementary resources for a research topic — beyond academic papers.

Everything here returns ONLY real, verifiable items fetched from live APIs/feeds,
or an empty list. Nothing is generated by an LLM, so a researcher never sees a
fabricated repo/article/video that doesn't exist.

* GitHub  — real repositories above a star threshold (GitHub Search API).
* Medium  — real recent posts from the topic's tag feed (Medium RSS).
* YouTube — real videos (YouTube Data API; only if YOUTUBE_API_KEY is set).

Company / market analysis is intentionally NOT included: there is no free,
authoritative source for it, and generating it with an LLM would risk
fabrication — which we explicitly avoid.
"""

import re
from concurrent.futures import ThreadPoolExecutor
from typing import List, Dict, Any

import requests

import sys
sys.path.insert(0, '..')
from config import GITHUB_MIN_STARS, GITHUB_TOKEN, YOUTUBE_API_KEY
from utils.cache import disk_cache
from utils.logging_config import get_logger

logger = get_logger(__name__)


# --------------------------------------------------------------------- GitHub
@disk_cache(namespace="github_repos")
def search_github_repos(topic: str, min_stars: int = None, max_results: int = 5) -> List[Dict[str, Any]]:
    """Real GitHub repositories for the topic, above a star threshold."""
    min_stars = GITHUB_MIN_STARS if min_stars is None else min_stars
    headers = {"Accept": "application/vnd.github+json", "User-Agent": "DeepArticle/1.0"}
    if GITHUB_TOKEN:
        headers["Authorization"] = f"Bearer {GITHUB_TOKEN}"
    try:
        r = requests.get(
            "https://api.github.com/search/repositories",
            params={"q": f"{topic} stars:>={min_stars}", "sort": "stars",
                    "order": "desc", "per_page": max_results},
            headers=headers, timeout=30,
        )
        r.raise_for_status()
        items = r.json().get("items", []) or []
        return [{
            "name": it.get("full_name", ""),
            "url": it.get("html_url", ""),
            "stars": it.get("stargazers_count", 0),
            "description": (it.get("description") or "").strip(),
            "language": it.get("language") or "",
        } for it in items]
    except Exception as e:
        logger.warning("GitHub search failed for %r: %s", topic, e)
        return []


# --------------------------------------------------------------------- Medium
def _slugify(text: str) -> str:
    return re.sub(r"-+", "-", re.sub(r"[^a-z0-9]+", "-", text.lower())).strip("-")


@disk_cache(namespace="medium_feed")
def search_medium(topic: str, max_results: int = 5) -> List[Dict[str, Any]]:
    """Real recent Medium posts from the topic's tag feed (empty if no such tag)."""
    # Try the full-topic tag, then a broader two-word tag.
    words = _slugify(topic).split("-")
    candidates = [_slugify(topic)]
    if len(words) >= 2:
        candidates.append("-".join(words[:2]))
    candidates.append(words[0] if words else "")

    for tag in [c for c in candidates if c]:
        try:
            r = requests.get(
                f"https://medium.com/feed/tag/{tag}",
                headers={"User-Agent": "Mozilla/5.0 DeepArticle/1.0"}, timeout=30,
            )
            if r.status_code != 200 or "<item>" not in r.text:
                continue
            items = _parse_rss(r.text, max_results)
            if items:
                return items
        except Exception as e:
            logger.debug("Medium feed failed for tag %r: %s", tag, e)
    return []


def _parse_rss(xml: str, max_results: int) -> List[Dict[str, Any]]:
    """Minimal RSS <item> parser (title/link/author/date)."""
    out = []
    for block in re.findall(r"<item>(.*?)</item>", xml, re.S)[:max_results]:
        def grab(tag):
            m = re.search(rf"<{tag}>(?:<!\[CDATA\[)?(.*?)(?:\]\]>)?</{tag}>", block, re.S)
            return (m.group(1).strip() if m else "")
        title = grab("title")
        link = grab("link")
        if title and link:
            out.append({
                "title": title,
                "url": link.split("?")[0],
                "author": grab("dc:creator"),
                "date": grab("pubDate")[:16],
            })
    return out


# -------------------------------------------------------------------- YouTube
@disk_cache(namespace="youtube_search")
def search_youtube(topic: str, max_results: int = 5) -> List[Dict[str, Any]]:
    """Real YouTube videos for the topic. Empty unless YOUTUBE_API_KEY is set."""
    if not YOUTUBE_API_KEY:
        return []
    try:
        r = requests.get(
            "https://www.googleapis.com/youtube/v3/search",
            params={"part": "snippet", "q": topic, "type": "video",
                    "maxResults": max_results, "key": YOUTUBE_API_KEY, "order": "relevance"},
            timeout=30,
        )
        r.raise_for_status()
        items = r.json().get("items", []) or []
        out = []
        for it in items:
            vid = (it.get("id") or {}).get("videoId")
            sn = it.get("snippet") or {}
            if vid:
                out.append({
                    "title": sn.get("title", ""),
                    "url": f"https://www.youtube.com/watch?v={vid}",
                    "channel": sn.get("channelTitle", ""),
                    "date": (sn.get("publishedAt") or "")[:10],
                })
        return out
    except Exception as e:
        logger.warning("YouTube search failed for %r: %s", topic, e)
        return []


# --------------------------------------------------------------------- gather
def gather_resources(topic: str) -> Dict[str, List[Dict[str, Any]]]:
    """Fetch GitHub repos, Medium articles and YouTube videos concurrently."""
    if not topic:
        return {"github": [], "articles": [], "videos": []}
    with ThreadPoolExecutor(max_workers=3) as ex:
        fg = ex.submit(search_github_repos, topic)
        fm = ex.submit(search_medium, topic)
        fy = ex.submit(search_youtube, topic)
        return {"github": fg.result(), "articles": fm.result(), "videos": fy.result()}
